### ISSUE TITLE
How to modify original object

### ISSUE THREAD

**Issue by rendomnet** [jhildenbiddle/mergician#3]
I want my object "b" to be merged to object "a" and mergician to return modified object "a" not a cloned object.

**Comment by jhildenbiddle** [comment]
Assign the merged object returned by `mergician` to object "a":

```js
let obj1 = { a: 1 };
let obj2 = { b: 2 };

obj1; // { a: 1 }

obj1 = mergician(obj1, obj2);

obj1; // { a: 1, b: 2 }
```
