### ISSUE TITLE
Mergician returns empty object after a merge with a class instance

### ISSUE THREAD

**Issue by HKGx** [jhildenbiddle/mergician#4]
```js
class Foo {
    bar() {
        return "baz"
    }
}

const merge = mergician();

merge({}, {
    specific: new Foo()
});
```

merge will return simply `{}`, is it intended?

**Comment by jhildenbiddle** [comment]
Hi @HKGx.

This is a bug. Thanks for creating the issue. I will have a fix out in the next few days. :)

**Comment by jhildenbiddle** [comment]
Hi again, @HKGx.

This issue has been addressed in v2. Thanks!
